apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace | quote }}
data:
  controller_manager_config.yaml: |-
    apiVersion: eks-iam-operator.neilmcgibbon.com/v1beta1
    kind: Config
    health:  
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
      resourceName: abe696a8.neilmcgibbon.com
    inlinePolicyNameOptions:
      prefix: {{ .Values.config.inlinePolicyNameOptions.prefix }}
      suffix: {{ .Values.config.inlinePolicyNameOptions.suffix }}
    roleNameOptions:
      prefix: {{ .Values.config.roleNameOptions.prefix }}
      suffix: {{ .Values.config.roleNameOptions.suffix }}
    oidc:
      providerArn: {{ .Values.config.oidc.providerArn }}
      issuerUrl: {{ .Values.config.oidc.issuerUrl }}
