apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-manager
rules:
- apiGroups:
  - eks-iam-operator.neilmcgibbon.com
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks-iam-operator.neilmcgibbon.com
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - eks-iam-operator.neilmcgibbon.com
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eks-iam-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "eks-iam-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eks-iam-operator.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "eks-iam-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eks-iam-operator.fullname" . }}-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eks-iam-operator.fullname" . }}-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "eks-iam-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
