apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "eks-iam-operator.selectorLabels" . | nindent 4 }}
  name: {{ include "eks-iam-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "eks-iam-operator.selectorLabels" . | nindent 4 }}