---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eks-iam-operator.neilmcgibbon.com
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks-iam-operator.neilmcgibbon.com
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - eks-iam-operator.neilmcgibbon.com
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
